<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSLk7fL2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSLk7fL2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSLk7fL2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSLk7fL2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSLk7fL2\App_KernelDevDebugContainer([
    'container.build_hash' => 'SLk7fL2',
    'container.build_id' => 'b396ab73',
    'container.build_time' => 1719564739,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSLk7fL2');
