<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYzuxafS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYzuxafS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYzuxafS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYzuxafS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYzuxafS\App_KernelDevDebugContainer([
    'container.build_hash' => 'YzuxafS',
    'container.build_id' => '4a1a2af8',
    'container.build_time' => 1719571558,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYzuxafS');
